### ISSUE TITLE
unspecific backend detection

### ISSUE THREAD

**Issue by Arnaudv6** [zyedidia/clipper#1]
Hi and thanks for micro: it is an awesome tool. (only waiting for tree-sitter syntax coloration)

Now to the topic:
my clipboard was acting weird under wayland... and works flawlessly now that I removed xclip.

Problem seems clipper/micro will use xclip if installed... even though presently running under a pure (no xwayland) wayland session.
https://github.com/zyedidia/clipper/blob/146cd955be6fe357066e83feac4d4604ad6b8d6c/xclip.go#L11
I think many clipboard bugs might® be related.

**Comment by zyedidia** [comment]
Hmm, what do you think you be the best solution? Should the priority be different, or is there a way to detect pure wayland vs xwayland? Maybe some environment variables may be set?

**Comment by Arnaudv6** [comment]
Yep, I carefully avoided saying what I'd do...
This should do the trick: https://stackoverflow.com/a/45537237

**Comment by zyedidia** [comment]
Thanks, it looks like it already checks that environment variable (I had forgotten), but Wayland should be checked before Xclip because xclip may still be available but not useful in a Wayland environment. Should be fixed now.
